import { TaskWithRelations, User } from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Romel Rey",
    email: "romel@example.com",
    timezone: "UTC",
    wip_limit: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Joy Doe",
    email: "joy@example.com",
    timezone: "UTC",
    wip_limit: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "John Smith",
    email: "john@example.com",
    timezone: "UTC",
    wip_limit: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockTags: string[] = [
  "frontend",
  "backend",
  "urgent",
  "bug",
  "feature",
  "design",
  "testing",
];

export const mockTasks: TaskWithRelations[] = [
  {
    id: "1",
    title: "Implement login page",
    description:
      "Create Next.js login with server actions and authentication flow.",
    board_id: "2",
    assignee_id: "1",
    creator_id: "1",
    priority: "high",
    due_date: "2025-01-15",
    position: 1,
    estimated_hours: 8,
    actual_hours: 6,
    created_at: "2025-01-01T10:00:00Z",
    updated_at: "2025-01-01T10:00:00Z",
    assignee: {
      id: "1",
      name: "Romel Rey",
      email: "romel@example.com",
      avatar_url: "",
      timezone: "UTC",
      wip_limit: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    board: {
      id: "2",
      name: "In Progress",
      slug: "in_progress",
      description: "Tasks currently being worked on",
      project_id: "1",
      position: 2,
      color: "#3B82F6",
      wip_limit: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    tags: [
      {
        id: "1",
        name: "frontend",
        color: "#10B981",
        project_id: "1",
        created_at: new Date().toISOString(),
      },
      {
        id: "2",
        name: "feature",
        color: "#8B5CF6",
        project_id: "1",
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "2",
    title: "Set up database schema",
    description:
      "Design and implement database tables for tasks, tags, and users with proper relationships.",
    board_id: "1",
    assignee_id: "2",
    creator_id: "1",
    priority: "medium",
    due_date: "2025-01-20",
    position: 1,
    estimated_hours: 12,
    actual_hours: undefined,
    created_at: "2025-01-01T11:00:00Z",
    updated_at: "2025-01-01T11:00:00Z",
    assignee: {
      id: "2",
      name: "Joy Doe",
      email: "joy@example.com",
      avatar_url: "",
      timezone: "UTC",
      wip_limit: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    board: {
      id: "1",
      name: "To Do",
      slug: "todo",
      description: "Tasks to be done",
      project_id: "1",
      position: 1,
      color: "#6B7280",
      wip_limit: undefined,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    tags: [
      {
        id: "3",
        name: "backend",
        color: "#F59E0B",
        project_id: "1",
        created_at: new Date().toISOString(),
      },
      {
        id: "4",
        name: "database",
        color: "#EF4444",
        project_id: "1",
        created_at: new Date().toISOString(),
      },
    ],
  },
];
